nome = str('Igor')
sobrenome = str('Viana')
ano_de_nascimento = int(1996)
idade = int(27)
maior_de_idade = idade >= 18
altura_em_metros = float(1.90)
print('Nome: ', nome)
print('Sobrenome: ', sobrenome)
print('Idade: ', idade)
print('Ano de nascimento: ', ano_de_nascimento)
print('É maior de idade: ', maior_de_idade)
print('Altura em metros: ', altura_em_metros)